name: SMBACK
on: 
  push:
   branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['4.4']
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name:  Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install --prefix server && npm install --prefix client --force
      - run: npm run build --prefix client
      - run: pm2 restart index.js --prefex server